name: Create org repo stats

permissions: write-all

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  push:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4

        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Use custom action to get data and update README
        uses: ./
        with:
          org-name: "TickLabVN"
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'Update README with org repo data'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
